### ISSUE TITLE
missing dependencies vec.hpp/half.hpp

### ISSUE THREAD

**Issue by Degot** [20k/OpenCLRenderer#2]
Hi,

 I'm trying to compile your code, but I can't deduct next libraries: vec/vec.hpp and half/half.hpp.
Where are they from?

**Comment by 20k** [comment]
Hello!

<vec/vec.hpp> is https://github.com/20k/funvectormaths

<half/half.hpp> is http://half.sourceforge.net/

If you run into any more dependency issues or this fixes your issue, let me know and I'll close this :) I should really compile a list somewhere
